sudo: false
language: python
python:
  - '3.5'
  
install:
  - pip install -U tox
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com

env:
  global:
    - RESULTS=results.xml{testing}
 
  matrix:
     - TESTENV=coveralls RESULTS="[$TESTENV]results.xml{testing} [$TESTENV]coverage.xml"
     - TESTENV=linting RESULTS=analysis.log{lint} #rst-output.txt
     - TESTENV=py26 
     - TESTENV=py27 
     - TESTENV=py33 
     - TESTENV=py34 
     - TESTENV=py35 
     - TESTENV=pypy 
     - TESTENV=py27-pexpect 
     - TESTENV=py27-xdist 
     - TESTENV=py27-trial 
     - TESTENV=py35-pexpect 
     - TESTENV=py35-xdist 
     - TESTENV=py35-trial 
     - TESTENV=py27-nobyte 
     - TESTENV=doctesting RESULTS=doc/results*.xml
  #  - TESTENV=freeze
  #  - TESTENV=docs 

matrix:
  include:
    - env: TESTENV=py36 
      python: 3.6-dev
    - env: TESTENV=py37
      python: nightly


script:
  - tox --recreate -e $TESTENV
  - testspace [$TESTENV]$RESULTS 
